# Generated by Django 4.1.1 on 2022-09-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
